# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'NovoLayout.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QStackedWidget,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1525, 749)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setGeometry(QRect(20, 10, 1481, 691))
        self.MainTab.setStyleSheet(u"background-color: #fff;\n"
"color: #000;")
        self.ConversionTab = QWidget()
        self.ConversionTab.setObjectName(u"ConversionTab")
        self.ConversionTab.setStyleSheet(u"")
        self.gridLayoutWidget = QWidget(self.ConversionTab)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(30, 40, 1411, 591))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.ConversionOptions = QStackedWidget(self.gridLayoutWidget)
        self.ConversionOptions.setObjectName(u"ConversionOptions")
        self.ConversionOptions.setStyleSheet(u"")
        self.main = QWidget()
        self.main.setObjectName(u"main")
        self.ConvertImagesButton = QPushButton(self.main)
        self.ConvertImagesButton.setObjectName(u"ConvertImagesButton")
        self.ConvertImagesButton.setGeometry(QRect(390, 250, 181, 121))
        self.ConvertImagesButton.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConvertAudioButton = QPushButton(self.main)
        self.ConvertAudioButton.setObjectName(u"ConvertAudioButton")
        self.ConvertAudioButton.setGeometry(QRect(790, 50, 181, 121))
        self.ConvertAudioButton.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConvertVideoButton = QPushButton(self.main)
        self.ConvertVideoButton.setObjectName(u"ConvertVideoButton")
        self.ConvertVideoButton.setGeometry(QRect(390, 50, 181, 121))
        self.ConvertVideoButton.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConvertDocumentButton = QPushButton(self.main)
        self.ConvertDocumentButton.setObjectName(u"ConvertDocumentButton")
        self.ConvertDocumentButton.setGeometry(QRect(790, 250, 181, 121))
        self.ConvertDocumentButton.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConversionOptions.addWidget(self.main)
        self.PageVideo = QWidget()
        self.PageVideo.setObjectName(u"PageVideo")
        self.label = QLabel(self.PageVideo)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(560, 20, 251, 51))
        font = QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DroppableVideoArea = QFrame(self.PageVideo)
        self.DroppableVideoArea.setObjectName(u"DroppableVideoArea")
        self.DroppableVideoArea.setGeometry(QRect(80, 230, 611, 181))
        self.DroppableVideoArea.setStyleSheet(u"background-color: rgb(154, 153, 150);")
        self.DroppableVideoArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.DroppableVideoArea.setFrameShadow(QFrame.Shadow.Raised)
        self.droppableVideoLabel = QLabel(self.DroppableVideoArea)
        self.droppableVideoLabel.setObjectName(u"droppableVideoLabel")
        self.droppableVideoLabel.setGeometry(QRect(0, 0, 611, 181))
        self.droppableVideoLabel.setStyleSheet(u"background-color: #eee;")
        self.droppableVideoLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.PageVideo)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(950, 130, 251, 51))
        font1 = QFont()
        font1.setPointSize(17)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ConvertToVideoFormatOptions = QFrame(self.PageVideo)
        self.ConvertToVideoFormatOptions.setObjectName(u"ConvertToVideoFormatOptions")
        self.ConvertToVideoFormatOptions.setGeometry(QRect(860, 200, 431, 231))
        self.ConvertToVideoFormatOptions.setStyleSheet(u"")
        self.ConvertToVideoFormatOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.ConvertToVideoFormatOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget = QWidget(self.ConvertToVideoFormatOptions)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 0, 421, 231))
        self.VideoFormats = QVBoxLayout(self.verticalLayoutWidget)
        self.VideoFormats.setObjectName(u"VideoFormats")
        self.VideoFormats.setContentsMargins(0, 0, 0, 0)
        self.convertWav = QRadioButton(self.verticalLayoutWidget)
        self.convertWav.setObjectName(u"convertWav")

        self.VideoFormats.addWidget(self.convertWav)

        self.convertMP4 = QRadioButton(self.verticalLayoutWidget)
        self.convertMP4.setObjectName(u"convertMP4")

        self.VideoFormats.addWidget(self.convertMP4)

        self.convertAVI = QRadioButton(self.verticalLayoutWidget)
        self.convertAVI.setObjectName(u"convertAVI")

        self.VideoFormats.addWidget(self.convertAVI)

        self.convertMOV = QRadioButton(self.verticalLayoutWidget)
        self.convertMOV.setObjectName(u"convertMOV")

        self.VideoFormats.addWidget(self.convertMOV)

        self.separateAudio = QCheckBox(self.PageVideo)
        self.separateAudio.setObjectName(u"separateAudio")
        self.separateAudio.setGeometry(QRect(860, 450, 431, 21))
        self.ConvertVideo = QPushButton(self.PageVideo)
        self.ConvertVideo.setObjectName(u"ConvertVideo")
        self.ConvertVideo.setGeometry(QRect(1190, 510, 171, 51))
        self.ConvertVideo.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.back_from_video = QPushButton(self.PageVideo)
        self.back_from_video.setObjectName(u"back_from_video")
        self.back_from_video.setGeometry(QRect(30, 30, 80, 23))
        self.back_from_video.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConversionOptions.addWidget(self.PageVideo)
        self.pageAudio = QWidget()
        self.pageAudio.setObjectName(u"pageAudio")
        self.ConversionOptions_2 = QStackedWidget(self.pageAudio)
        self.ConversionOptions_2.setObjectName(u"ConversionOptions_2")
        self.ConversionOptions_2.setGeometry(QRect(0, 0, 1409, 589))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.ConvertImagesButton_2 = QPushButton(self.page_3)
        self.ConvertImagesButton_2.setObjectName(u"ConvertImagesButton_2")
        self.ConvertImagesButton_2.setGeometry(QRect(610, 380, 181, 121))
        self.ConvertAudioButton_2 = QPushButton(self.page_3)
        self.ConvertAudioButton_2.setObjectName(u"ConvertAudioButton_2")
        self.ConvertAudioButton_2.setGeometry(QRect(610, 210, 181, 121))
        self.ConvertVideoButton_2 = QPushButton(self.page_3)
        self.ConvertVideoButton_2.setObjectName(u"ConvertVideoButton_2")
        self.ConvertVideoButton_2.setGeometry(QRect(610, 40, 181, 121))
        self.ConversionOptions_2.addWidget(self.page_3)
        self.PageVideo_2 = QWidget()
        self.PageVideo_2.setObjectName(u"PageVideo_2")
        self.label_3 = QLabel(self.PageVideo_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(560, 20, 251, 51))
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DroppableAudioArea = QFrame(self.PageVideo_2)
        self.DroppableAudioArea.setObjectName(u"DroppableAudioArea")
        self.DroppableAudioArea.setGeometry(QRect(80, 230, 611, 181))
        self.DroppableAudioArea.setStyleSheet(u"background-color: rgb(154, 153, 150);")
        self.DroppableAudioArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.DroppableAudioArea.setFrameShadow(QFrame.Shadow.Raised)
        self.droppableVideoLabel_2 = QLabel(self.DroppableAudioArea)
        self.droppableVideoLabel_2.setObjectName(u"droppableVideoLabel_2")
        self.droppableVideoLabel_2.setGeometry(QRect(0, 0, 611, 181))
        self.droppableVideoLabel_2.setStyleSheet(u"background-color: #eee;")
        self.droppableVideoLabel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.PageVideo_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(950, 130, 251, 51))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ConvertToAudioFormatOptions = QFrame(self.PageVideo_2)
        self.ConvertToAudioFormatOptions.setObjectName(u"ConvertToAudioFormatOptions")
        self.ConvertToAudioFormatOptions.setGeometry(QRect(860, 200, 431, 231))
        self.ConvertToAudioFormatOptions.setStyleSheet(u"")
        self.ConvertToAudioFormatOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.ConvertToAudioFormatOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_2 = QWidget(self.ConvertToAudioFormatOptions)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 0, 421, 231))
        self.AudioFormats = QVBoxLayout(self.verticalLayoutWidget_2)
        self.AudioFormats.setObjectName(u"AudioFormats")
        self.AudioFormats.setContentsMargins(0, 0, 0, 0)
        self.convertMP3 = QRadioButton(self.verticalLayoutWidget_2)
        self.convertMP3.setObjectName(u"convertMP3")

        self.AudioFormats.addWidget(self.convertMP3)

        self.convertWAV = QRadioButton(self.verticalLayoutWidget_2)
        self.convertWAV.setObjectName(u"convertWAV")

        self.AudioFormats.addWidget(self.convertWAV)

        self.convertFlac = QRadioButton(self.verticalLayoutWidget_2)
        self.convertFlac.setObjectName(u"convertFlac")

        self.AudioFormats.addWidget(self.convertFlac)

        self.ConvertAudio = QPushButton(self.PageVideo_2)
        self.ConvertAudio.setObjectName(u"ConvertAudio")
        self.ConvertAudio.setGeometry(QRect(1190, 510, 171, 51))
        self.ConvertAudio.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.back_from_audio = QPushButton(self.PageVideo_2)
        self.back_from_audio.setObjectName(u"back_from_audio")
        self.back_from_audio.setGeometry(QRect(30, 30, 80, 23))
        self.back_from_audio.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.ConversionOptions_2.addWidget(self.PageVideo_2)
        self.ConversionOptions.addWidget(self.pageAudio)
        self.pageImage = QWidget()
        self.pageImage.setObjectName(u"pageImage")
        self.ConversionOptions_3 = QStackedWidget(self.pageImage)
        self.ConversionOptions_3.setObjectName(u"ConversionOptions_3")
        self.ConversionOptions_3.setGeometry(QRect(1390, 40, 1409, 589))
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.ConvertImagesButton_5 = QPushButton(self.page_9)
        self.ConvertImagesButton_5.setObjectName(u"ConvertImagesButton_5")
        self.ConvertImagesButton_5.setGeometry(QRect(610, 380, 181, 121))
        self.ConvertAudioButton_5 = QPushButton(self.page_9)
        self.ConvertAudioButton_5.setObjectName(u"ConvertAudioButton_5")
        self.ConvertAudioButton_5.setGeometry(QRect(610, 210, 181, 121))
        self.ConvertVideoButton_5 = QPushButton(self.page_9)
        self.ConvertVideoButton_5.setObjectName(u"ConvertVideoButton_5")
        self.ConvertVideoButton_5.setGeometry(QRect(610, 40, 181, 121))
        self.ConversionOptions_3.addWidget(self.page_9)
        self.PageVideo_5 = QWidget()
        self.PageVideo_5.setObjectName(u"PageVideo_5")
        self.label_9 = QLabel(self.PageVideo_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(560, 20, 251, 51))
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DroppableAudioArea_3 = QFrame(self.PageVideo_5)
        self.DroppableAudioArea_3.setObjectName(u"DroppableAudioArea_3")
        self.DroppableAudioArea_3.setGeometry(QRect(80, 230, 611, 181))
        self.DroppableAudioArea_3.setStyleSheet(u"background-color: rgb(154, 153, 150);")
        self.DroppableAudioArea_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.DroppableAudioArea_3.setFrameShadow(QFrame.Shadow.Raised)
        self.droppableVideoLabel_5 = QLabel(self.DroppableAudioArea_3)
        self.droppableVideoLabel_5.setObjectName(u"droppableVideoLabel_5")
        self.droppableVideoLabel_5.setGeometry(QRect(0, 70, 601, 51))
        self.droppableVideoLabel_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.PageVideo_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(950, 130, 251, 51))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ConvertToAudioFormatOptions_3 = QFrame(self.PageVideo_5)
        self.ConvertToAudioFormatOptions_3.setObjectName(u"ConvertToAudioFormatOptions_3")
        self.ConvertToAudioFormatOptions_3.setGeometry(QRect(860, 200, 431, 231))
        self.ConvertToAudioFormatOptions_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.ConvertToAudioFormatOptions_3.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_5 = QWidget(self.ConvertToAudioFormatOptions_3)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(0, 0, 431, 231))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.convertMP3_3 = QRadioButton(self.verticalLayoutWidget_5)
        self.convertMP3_3.setObjectName(u"convertMP3_3")

        self.verticalLayout_5.addWidget(self.convertMP3_3)

        self.convertWAV_3 = QRadioButton(self.verticalLayoutWidget_5)
        self.convertWAV_3.setObjectName(u"convertWAV_3")

        self.verticalLayout_5.addWidget(self.convertWAV_3)

        self.convertFlac_3 = QRadioButton(self.verticalLayoutWidget_5)
        self.convertFlac_3.setObjectName(u"convertFlac_3")

        self.verticalLayout_5.addWidget(self.convertFlac_3)

        self.ConvertAudio_3 = QPushButton(self.PageVideo_5)
        self.ConvertAudio_3.setObjectName(u"ConvertAudio_3")
        self.ConvertAudio_3.setGeometry(QRect(1190, 510, 171, 51))
        self.ConversionOptions_3.addWidget(self.PageVideo_5)
        self.ConversionOptions_5 = QStackedWidget(self.pageImage)
        self.ConversionOptions_5.setObjectName(u"ConversionOptions_5")
        self.ConversionOptions_5.setGeometry(QRect(0, 0, 1409, 589))
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.ConvertImagesButton_6 = QPushButton(self.page_10)
        self.ConvertImagesButton_6.setObjectName(u"ConvertImagesButton_6")
        self.ConvertImagesButton_6.setGeometry(QRect(610, 380, 181, 121))
        self.ConvertAudioButton_6 = QPushButton(self.page_10)
        self.ConvertAudioButton_6.setObjectName(u"ConvertAudioButton_6")
        self.ConvertAudioButton_6.setGeometry(QRect(610, 210, 181, 121))
        self.ConvertVideoButton_6 = QPushButton(self.page_10)
        self.ConvertVideoButton_6.setObjectName(u"ConvertVideoButton_6")
        self.ConvertVideoButton_6.setGeometry(QRect(610, 40, 181, 121))
        self.ConversionOptions_5.addWidget(self.page_10)
        self.PageVideo_6 = QWidget()
        self.PageVideo_6.setObjectName(u"PageVideo_6")
        self.label_11 = QLabel(self.PageVideo_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(560, 20, 251, 51))
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DroppableImageArea = QFrame(self.PageVideo_6)
        self.DroppableImageArea.setObjectName(u"DroppableImageArea")
        self.DroppableImageArea.setGeometry(QRect(80, 230, 611, 181))
        self.DroppableImageArea.setStyleSheet(u"background-color: rgb(154, 153, 150);")
        self.DroppableImageArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.DroppableImageArea.setFrameShadow(QFrame.Shadow.Raised)
        self.droppableVideoLabel_6 = QLabel(self.DroppableImageArea)
        self.droppableVideoLabel_6.setObjectName(u"droppableVideoLabel_6")
        self.droppableVideoLabel_6.setGeometry(QRect(0, 0, 611, 181))
        self.droppableVideoLabel_6.setStyleSheet(u"background-color: #eee;")
        self.droppableVideoLabel_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.PageVideo_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(950, 130, 251, 51))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ConvertToAudioFormatOptions_4 = QFrame(self.PageVideo_6)
        self.ConvertToAudioFormatOptions_4.setObjectName(u"ConvertToAudioFormatOptions_4")
        self.ConvertToAudioFormatOptions_4.setGeometry(QRect(860, 200, 431, 231))
        self.ConvertToAudioFormatOptions_4.setStyleSheet(u"")
        self.ConvertToAudioFormatOptions_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.ConvertToAudioFormatOptions_4.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_6 = QWidget(self.ConvertToAudioFormatOptions_4)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(10, 0, 421, 231))
        self.ImageFormats = QVBoxLayout(self.verticalLayoutWidget_6)
        self.ImageFormats.setObjectName(u"ImageFormats")
        self.ImageFormats.setContentsMargins(0, 0, 0, 0)
        self.convertPNG = QRadioButton(self.verticalLayoutWidget_6)
        self.convertPNG.setObjectName(u"convertPNG")

        self.ImageFormats.addWidget(self.convertPNG)

        self.convertJPG = QRadioButton(self.verticalLayoutWidget_6)
        self.convertJPG.setObjectName(u"convertJPG")

        self.ImageFormats.addWidget(self.convertJPG)

        self.convertWEBP = QRadioButton(self.verticalLayoutWidget_6)
        self.convertWEBP.setObjectName(u"convertWEBP")

        self.ImageFormats.addWidget(self.convertWEBP)

        self.ConvertImage = QPushButton(self.PageVideo_6)
        self.ConvertImage.setObjectName(u"ConvertImage")
        self.ConvertImage.setGeometry(QRect(1190, 510, 171, 51))
        self.ConvertImage.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.upscale2x = QCheckBox(self.PageVideo_6)
        self.upscale2x.setObjectName(u"upscale2x")
        self.upscale2x.setGeometry(QRect(870, 450, 83, 21))
        self.upscale4x = QCheckBox(self.PageVideo_6)
        self.upscale4x.setObjectName(u"upscale4x")
        self.upscale4x.setGeometry(QRect(990, 450, 83, 21))
        self.back_from_image = QPushButton(self.PageVideo_6)
        self.back_from_image.setObjectName(u"back_from_image")
        self.back_from_image.setGeometry(QRect(30, 30, 80, 23))
        self.back_from_image.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.remove_whitespace = QCheckBox(self.PageVideo_6)
        self.remove_whitespace.setObjectName(u"remove_whitespace")
        self.remove_whitespace.setGeometry(QRect(1090, 450, 181, 21))
        self.ConversionOptions_5.addWidget(self.PageVideo_6)
        self.ConversionOptions.addWidget(self.pageImage)
        self.PagePDF = QWidget()
        self.PagePDF.setObjectName(u"PagePDF")
        self.label_18 = QLabel(self.PagePDF)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(560, 20, 251, 51))
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.back_from_document = QPushButton(self.PagePDF)
        self.back_from_document.setObjectName(u"back_from_document")
        self.back_from_document.setGeometry(QRect(30, 30, 80, 23))
        self.back_from_document.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.DroppableDocumentArea = QFrame(self.PagePDF)
        self.DroppableDocumentArea.setObjectName(u"DroppableDocumentArea")
        self.DroppableDocumentArea.setGeometry(QRect(80, 230, 611, 181))
        self.DroppableDocumentArea.setStyleSheet(u"background-color: rgb(154, 153, 150);")
        self.DroppableDocumentArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.DroppableDocumentArea.setFrameShadow(QFrame.Shadow.Raised)
        self.droppableVideoLabel_9 = QLabel(self.DroppableDocumentArea)
        self.droppableVideoLabel_9.setObjectName(u"droppableVideoLabel_9")
        self.droppableVideoLabel_9.setGeometry(QRect(0, 0, 611, 181))
        self.droppableVideoLabel_9.setStyleSheet(u"background-color: #eee;")
        self.droppableVideoLabel_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.PagePDF)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(950, 130, 251, 51))
        self.label_19.setFont(font1)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ConvertToDocumentFormatOptions = QFrame(self.PagePDF)
        self.ConvertToDocumentFormatOptions.setObjectName(u"ConvertToDocumentFormatOptions")
        self.ConvertToDocumentFormatOptions.setGeometry(QRect(860, 200, 431, 231))
        self.ConvertToDocumentFormatOptions.setStyleSheet(u"")
        self.ConvertToDocumentFormatOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.ConvertToDocumentFormatOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_9 = QWidget(self.ConvertToDocumentFormatOptions)
        self.verticalLayoutWidget_9.setObjectName(u"verticalLayoutWidget_9")
        self.verticalLayoutWidget_9.setGeometry(QRect(10, 0, 421, 231))
        self.documentFormats = QVBoxLayout(self.verticalLayoutWidget_9)
        self.documentFormats.setObjectName(u"documentFormats")
        self.documentFormats.setContentsMargins(0, 0, 0, 0)
        self.convertPDF = QRadioButton(self.verticalLayoutWidget_9)
        self.convertPDF.setObjectName(u"convertPDF")

        self.documentFormats.addWidget(self.convertPDF)

        self.convertDOCX = QRadioButton(self.verticalLayoutWidget_9)
        self.convertDOCX.setObjectName(u"convertDOCX")

        self.documentFormats.addWidget(self.convertDOCX)

        self.convertDOC = QRadioButton(self.verticalLayoutWidget_9)
        self.convertDOC.setObjectName(u"convertDOC")

        self.documentFormats.addWidget(self.convertDOC)

        self.convertDocument = QPushButton(self.PagePDF)
        self.convertDocument.setObjectName(u"convertDocument")
        self.convertDocument.setGeometry(QRect(1190, 510, 171, 51))
        self.convertDocument.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.document_file_name = QLineEdit(self.PagePDF)
        self.document_file_name.setObjectName(u"document_file_name")
        self.document_file_name.setGeometry(QRect(860, 450, 431, 31))
        self.document_file_name.setStyleSheet(u"")
        self.ConversionOptions.addWidget(self.PagePDF)

        self.gridLayout.addWidget(self.ConversionOptions, 0, 0, 1, 1)

        self.MainTab.addTab(self.ConversionTab, "")
        self.DownloadTab = QWidget()
        self.DownloadTab.setObjectName(u"DownloadTab")
        self.label_13 = QLabel(self.DownloadTab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(560, 50, 321, 71))
        self.label_13.setFont(font)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.youtubeURL = QLineEdit(self.DownloadTab)
        self.youtubeURL.setObjectName(u"youtubeURL")
        self.youtubeURL.setGeometry(QRect(440, 120, 551, 51))
        self.youtubeURL.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.downloadMP4 = QCheckBox(self.DownloadTab)
        self.downloadMP4.setObjectName(u"downloadMP4")
        self.downloadMP4.setGeometry(QRect(450, 210, 121, 21))
        self.downloadMP3 = QCheckBox(self.DownloadTab)
        self.downloadMP3.setObjectName(u"downloadMP3")
        self.downloadMP3.setGeometry(QRect(450, 240, 121, 21))
        self.downloadVideoFromYoutube = QPushButton(self.DownloadTab)
        self.downloadVideoFromYoutube.setObjectName(u"downloadVideoFromYoutube")
        self.downloadVideoFromYoutube.setGeometry(QRect(590, 430, 231, 71))
        self.downloadVideoFromYoutube.setStyleSheet(u"background-color: rgb(223, 223, 223);")
        self.MainTab.addTab(self.DownloadTab, "")
        self.OrganizeTab = QWidget()
        self.OrganizeTab.setObjectName(u"OrganizeTab")
        self.label_14 = QLabel(self.OrganizeTab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(540, 40, 321, 71))
        self.label_14.setFont(font)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.select_folder_to_organize = QPushButton(self.OrganizeTab)
        self.select_folder_to_organize.setObjectName(u"select_folder_to_organize")
        self.select_folder_to_organize.setGeometry(QRect(530, 250, 341, 101))
        self.MainTab.addTab(self.OrganizeTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1525, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(0)
        self.ConversionOptions.setCurrentIndex(3)
        self.ConversionOptions_2.setCurrentIndex(1)
        self.ConversionOptions_3.setCurrentIndex(1)
        self.ConversionOptions_5.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Convertt", None))
        self.ConvertImagesButton.setText(QCoreApplication.translate("MainWindow", u"Imagem", None))
        self.ConvertAudioButton.setText(QCoreApplication.translate("MainWindow", u"Audio", None))
        self.ConvertVideoButton.setText(QCoreApplication.translate("MainWindow", u"V\u00eddeo", None))
        self.ConvertDocumentButton.setText(QCoreApplication.translate("MainWindow", u"Documento", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Converter V\u00eddeo", None))
        self.droppableVideoLabel.setText(QCoreApplication.translate("MainWindow", u"Clique ou arraste um arquivo aqui", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Converter para:", None))
        self.convertWav.setText(QCoreApplication.translate("MainWindow", u"WMV", None))
        self.convertMP4.setText(QCoreApplication.translate("MainWindow", u"MP4", None))
        self.convertAVI.setText(QCoreApplication.translate("MainWindow", u"AVI", None))
        self.convertMOV.setText(QCoreApplication.translate("MainWindow", u"MOV", None))
        self.separateAudio.setText(QCoreApplication.translate("MainWindow", u"Renderizar arquivo de \u00e1udio separado", None))
        self.ConvertVideo.setText(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.back_from_video.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.ConvertImagesButton_2.setText(QCoreApplication.translate("MainWindow", u"Converter Imagem", None))
        self.ConvertAudioButton_2.setText(QCoreApplication.translate("MainWindow", u"Converter Audio", None))
        self.ConvertVideoButton_2.setText(QCoreApplication.translate("MainWindow", u"Converter V\u00eddeo", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Converter \u00c1udio", None))
        self.droppableVideoLabel_2.setText(QCoreApplication.translate("MainWindow", u"Clique ou arraste um arquivo aqui", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Converter para:", None))
        self.convertMP3.setText(QCoreApplication.translate("MainWindow", u"MP3", None))
        self.convertWAV.setText(QCoreApplication.translate("MainWindow", u"WAV", None))
        self.convertFlac.setText(QCoreApplication.translate("MainWindow", u"FLAC", None))
        self.ConvertAudio.setText(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.back_from_audio.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.ConvertImagesButton_5.setText(QCoreApplication.translate("MainWindow", u"Converter Imagem", None))
        self.ConvertAudioButton_5.setText(QCoreApplication.translate("MainWindow", u"Converter Audio", None))
        self.ConvertVideoButton_5.setText(QCoreApplication.translate("MainWindow", u"Converter V\u00eddeo", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Converter \u00c1udio", None))
        self.droppableVideoLabel_5.setText(QCoreApplication.translate("MainWindow", u"Clique ou arraste um arquivo aqui", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Converter para:", None))
        self.convertMP3_3.setText(QCoreApplication.translate("MainWindow", u"MP3", None))
        self.convertWAV_3.setText(QCoreApplication.translate("MainWindow", u"WAV", None))
        self.convertFlac_3.setText(QCoreApplication.translate("MainWindow", u"FLAC", None))
        self.ConvertAudio_3.setText(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.ConvertImagesButton_6.setText(QCoreApplication.translate("MainWindow", u"Converter Imagem", None))
        self.ConvertAudioButton_6.setText(QCoreApplication.translate("MainWindow", u"Converter Audio", None))
        self.ConvertVideoButton_6.setText(QCoreApplication.translate("MainWindow", u"Converter V\u00eddeo", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Converter Imagem", None))
        self.droppableVideoLabel_6.setText(QCoreApplication.translate("MainWindow", u"Clique ou arraste um arquivo aqui", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Converter para:", None))
        self.convertPNG.setText(QCoreApplication.translate("MainWindow", u"PNG", None))
        self.convertJPG.setText(QCoreApplication.translate("MainWindow", u"JPG", None))
        self.convertWEBP.setText(QCoreApplication.translate("MainWindow", u"WEBP", None))
        self.ConvertImage.setText(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.upscale2x.setText(QCoreApplication.translate("MainWindow", u"upscale 2x", None))
        self.upscale4x.setText(QCoreApplication.translate("MainWindow", u"upscale 4x", None))
        self.back_from_image.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.remove_whitespace.setText(QCoreApplication.translate("MainWindow", u"remover espa\u00e7o em branco", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Converter Documento", None))
        self.back_from_document.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.droppableVideoLabel_9.setText(QCoreApplication.translate("MainWindow", u"Clique ou arraste um arquivo aqui", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Converter para:", None))
        self.convertPDF.setText(QCoreApplication.translate("MainWindow", u"PDF", None))
        self.convertDOCX.setText(QCoreApplication.translate("MainWindow", u"DOCX", None))
        self.convertDOC.setText(QCoreApplication.translate("MainWindow", u"DOC", None))
        self.convertDocument.setText(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.document_file_name.setText("")
        self.document_file_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nome do arquivo", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.ConversionTab), QCoreApplication.translate("MainWindow", u"Converter", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Baixar do youtube", None))
        self.youtubeURL.setText("")
        self.youtubeURL.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Cole o link do v\u00eddeo aqui", None))
        self.downloadMP4.setText(QCoreApplication.translate("MainWindow", u"Baixar V\u00eddeo", None))
        self.downloadMP3.setText(QCoreApplication.translate("MainWindow", u"Baixar Audio", None))
        self.downloadVideoFromYoutube.setText(QCoreApplication.translate("MainWindow", u"Baixar", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.DownloadTab), QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Organizar pastas", None))
        self.select_folder_to_organize.setText(QCoreApplication.translate("MainWindow", u"Clique para selecionar uma pasta", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.OrganizeTab), QCoreApplication.translate("MainWindow", u"Organizar", None))
    # retranslateUi

